name: CI

on: push

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: "1.18"
            otp: "28"
          - elixir: "1.18"
            otp: "27"
          - elixir: "1.17"
            otp: "27"
          - elixir: "1.16"
            otp: "26"
          - elixir: "1.15.6"
            otp: "25.3.2.6"
          - elixir: "1.15.6"
            otp: "24.3.4.13"
          - elixir: "1.20.0"
            otp: "27.3.4.11"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Elixir and Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Restore deps and _build cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-
      - name: Install dependencies
        run: mix deps.get
      - name: Compile deps
        run: mix deps.compile
      - name: Run tests
        run: mix test
      - name: Check format
        run: mix format --check-formatted
      - name: Check quality
        run: mix credo --all --strict || true
